package com.standardgeneral.android.spanishcorewords;
import java.util.Map;

public class Words {
    public static void addWords(Map map){
        map.put("el, la", "the");
        map.put("de", "of");
        map.put("che (conjunction)", "that");
        map.put("y", "and");
        map.put("a", "to");
        map.put("en", "in");
        map.put("un", "a");
        map.put("es (verb)", "its");
        map.put("no", "not");
        map.put("haber", "to have");
        map.put("ha", "he has, she has");
        map.put("por", "for");
        map.put("con", "with");
        map.put("su", "his, her, their, your");
        map.put("para", "for");
        map.put("como", "like");
        map.put("está", "he is");
        map.put("tener", "to have");
        map.put("le", "to him");
        map.put("lo", "the");
        map.put("todo", "all");
        map.put("pero", "but");
        map.put("más", "more");
        map.put("hacer", "to do");
        map.put("o", "or");
        map.put("poder", "can");
        map.put("decir", "say");
        map.put("este", "this");
        map.put("ir", "go");
        map.put("otro", "other");
        map.put("ese", "that");
        map.put("la (pronoun)", "her");
        map.put("si", "if");
        map.put("me", "me");
        map.put("ya", "already");
        map.put("ver", "see");
        map.put("porque", "because");
        map.put("dar", "give");
        map.put("cuando", "when");
        map.put("él", "he");
        map.put("ellos", "them");
        map.put("muy", "very");
        map.put("sin", "without");
        map.put("vez", "time (occurance)");
        map.put("mucho", "much");
        map.put("saber", "know");
        map.put("qué", "what, which, how");
        map.put("sobre", "on top of, over, about");
        map.put("mi", "my");
        map.put("alguno", "some");
        map.put("mismo", "same");
        map.put("yo", "I");
        map.put("también", "also");
        map.put("hasta", "until");
        map.put("año", "year");
        map.put("dos", "two");
        map.put("quiero", "I want");
        map.put("entre", "among");
        map.put("así", "like that");
        map.put("primero", "first");
        map.put("desde", "since");
        map.put("grande", "large");
        map.put("eso", "that");
        map.put("ni", "not even");
        map.put("nos", "us");
        map.put("llegar", "arrive");
        map.put("pasar", "pass");
        map.put("tiempo", "time");
        map.put("ella", "she");
        map.put("sí", "yes");
        map.put("día", "day");
        map.put("uno", "one");
        map.put("bien", "well");
        map.put("poco", "little, few");
        map.put("deber", "should, ought to, owe");
        map.put("entonces", "so, then");

    }
}
